import { NAME } from "./constants";

export const GET_MOVIES = `${NAME}.GET_MOVIES`;
export const GET_MOVIES_SUCCESS = `${NAME}.GET_MOVIES_SUCCESS`;
export const GET_MOVIES_FAILURE = `${NAME}.GET_MOVIES_FAILURE`;


export const GET_SINGLE_MOVIE = `${NAME}.GET_SINGLE_MOVIE`;
export const GET_SINGLE_MOVIE_SUCCESS = `${NAME}.GET_SINGLE_MOVIE_SUCCESS`;
export const GET_SINGLE_MOVIE_FAILURE = `${NAME}.GET_SINGLE_MOVIE_FAILURE`;


export const TOGGLE_FAVORITE = `${NAME}.TOGGLE_FAVORITE`;